Repository polyseam/cndi, pull requests merged in 2023-09, with the labels that each got.

#501 [Target]: GKE
  src/constants.ts
  src/outputs/readme.ts
  src/outputs/terraform/gcp-gke/cndi_argocd_admin_password_secret_manifest.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_argocd_helm_chart.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_argocd_private_repo_secret_manifest.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_argocd_root_application_manifest.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_bcrypt_hash_argocd_admin_password.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_cert_manager_helm_chart.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_gke_cluster.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_google_compute_address.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_google_compute_network.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_google_compute_subnetwork.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_google_project_service_cloudresourcemanager.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_google_project_service_compute.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_google_project_service_k8s.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_nginx_controller_helm_chart.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_outputs.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_sealed_secrets_helm_chart.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_sealed_secrets_secret_manifest.tf.json.ts
  src/outputs/terraform/gcp-gke/cndi_time_static_admin_password_update.tf.json.ts
  src/outputs/terraform/gcp-gke/data.tf.json.ts
  src/outputs/terraform/gcp-gke/locals.tf.json.ts
  src/outputs/terraform/gcp-gke/provider.tf.json.ts
  src/outputs/terraform/gcp-gke/stageAll.ts
  src/outputs/terraform/gcp-gke/terraform.tf.json.ts
  src/outputs/terraform/stageTerraformResourcesForConfig.ts
  src/schemas/cndi-config.schema.json
  src/templates/gke/airflow.yaml
  src/templates/gke/basic.yaml
  src/templates/gke/cnpg.yaml
  src/templates/gke/hop.yaml
  src/templates/gke/mongodb.yaml
  src/templates/gke/mysql.yaml
  src/templates/gke/neo4j.yaml
  src/templates/knownTemplates.ts
  src/templates/useTemplate.ts
  src/types.ts
  src/utils.ts
Labels: deployment target

#494 [Template]: Redis | [Template]: Superset
  src/templates/azure/apache-superset.yaml
  src/templates/azure/redis.yaml
  src/templates/ec2/apache-superset.yaml
  src/templates/ec2/redis.yaml
  src/templates/eks/apache-superset.yaml
  src/templates/eks/redis.yaml
  src/templates/gcp/apache-superset.yaml
  src/templates/gcp/redis.yaml
Labels: template

#509 GitHub Discussion for every CLI error
  README.md
  docs/error-code-reference.json
  src/commands/init.ts
  src/constants.ts
  src/deployment-targets/shared.ts
  src/outputs/terraform/azure-aks/stageAll.ts
  src/outputs/terraform/gcp-gke/stageAll.ts
  src/templates/useTemplate.ts
  src/utils.ts
Labels: documentation, enhancement
