Repository polyseam/cndi, pull requests merged in 2024-06, with the labels that each got.

#919 [Bug]: Fix pattern matching in dynamic get_block() calls
  src/use-template/mod.ts
Labels: bug

#920 [Enhancement]: Upgrade `ArgoCD` Chart
  src/constants.ts
  src/outputs/terraform/aws/AWSEKSStack.ts
  src/outputs/terraform/azure/AzureAKSStack.ts
  src/outputs/terraform/gcp/GCPGKEStack.ts
Labels: enhancement

#923 Configure Airflow fernet key and webserver secret key
  templates/airflow.yaml
Labels: enhancement

#927 [Enhancement]: remove `TERRAFORM_STATE_PASSPHRASE` prompt
  blocks/common/cluster/core-prompts.yaml
  blocks/common/cluster/env.yaml
Labels: enhancement

#930 [Enhancement]: Grow charset in random generation
  src/use-template/mod.ts
  src/utils.ts
Labels: enhancement

#931 [Enhancement]: Use `identity: SystemAssigned` instead of user principal keys
  src/outputs/terraform/azure/AzureAKSStack.ts
Labels: enhancement, azure

#936 [Bug]: fix non-string prompt responses being wrapped in quotes
  src/use-template/mod.ts
Labels: bug
