Repository polyseam/cndi, pull requests merged in 2024-05, with the labels that each got.

#834 [Build]: all deps aliased in deno.json[imports]
  deno.json
  deno.lock
  src/deps.ts
  src/outputs/terraform/cdktf-deps.ts
Labels: build

#842 [Docs]: Template Authoring Doc
  docs/template-authoring.md
Labels: documentation

#843 [Template]: Coder
  templates/coder.yaml
Labels: enhancement, template

#844 [Fix]: fix missing default `distrbution` value for dev `provider`
  src/use-template/mod.ts
Labels: bug

#849 [Enhancement]: Validation with Checkov
  src/commands/create.ts
  src/commands/init.ts
  src/outputs/cndi-onpull-workflow.ts
Labels: enhancement

#852 [Fix]: Allow Deploying multiple GKE clusters to the same GCP Project
  src/outputs/terraform/gcp/GCPGKEStack.ts
  src/use-template/util/validation.ts
  src/utils.ts
  src/validate/cndiConfig.ts
Labels: bug

#853 [Fix]: Disable GKE Cluster `deletion_protection`
  src/actions/overwrite.worker.ts
  src/constants.ts
  src/outputs/core-applications/private-nginx.application.yaml.ts
  src/outputs/core-applications/public-nginx.application.yaml.ts
  src/outputs/custom-port-manifests/managed/ingress-service-private.ts
  src/outputs/custom-port-manifests/managed/ingress-service-public.ts
  src/outputs/custom-port-manifests/managed/ingress-tcp-services-configmap-private.ts
  src/outputs/custom-port-manifests/managed/ingress-tcp-services-configmap-public.ts
  src/outputs/terraform/aws/AWSEKSStack.ts
  src/outputs/terraform/azure/AzureAKSStack.ts
  src/outputs/terraform/gcp/GCPGKEStack.ts
  src/types.ts
Labels: bug

#866 fix typos
  README.md
  docs/template-authoring.md
Labels: documentation

#867 add info about installing gh cli
  README.md
Labels: documentation

#876 add discord link to install.md
  docs/install.md
Labels: documentation

#880 [Enhancement]: Clusterless IaC
  cndi_config.yaml
  src/actions/overwrite.worker.ts
  src/commands/create.ts
  src/commands/init.ts
  src/commands/overwrite.ts
  src/outputs/cndi-run-workflow.ts
  src/outputs/core-applications/private-nginx.application.yaml.ts
  src/outputs/core-applications/public-nginx.application.yaml.ts
  src/outputs/dotenv.ts
  src/outputs/terraform/aws/AWSClusterlessStack.ts
  src/outputs/terraform/azure/AzureClusterlessStack.ts
  src/outputs/terraform/gcp/GCPClusterlessStack.ts
  src/outputs/terraform/stageTerraformResourcesForConfig.ts
  src/schemas/cndi_config.schema.json
  src/types.ts
  src/validate/cndiConfig.ts
Labels: enhancement

#879 [Enhancement]: Update and standardize rwm/rwo storage classes and config for GKE, Azure, AWS, and Airflow
  src/outputs/terraform/aws/AWSEKSStack.ts
  src/outputs/terraform/azure/AzureAKSStack.ts
  src/outputs/terraform/gcp/GCPGKEStack.ts
  templates/airflow.yaml
Labels: enhancement

#888 [Build]: Fix issue where existing build artifacts were not cleaned during new builds
  deno.json
Labels: bug, build

#913 [Enhancement] Upgrade deno to v1.44
  .github/workflows/bin-build.yaml
  .github/workflows/gh-release.yaml
  .github/workflows/main-latest.yaml
  .github/workflows/main-pull.yml
  deno.json
Labels: enhancement, build
