Repository polyseam/cndi, pull requests merged in 2024-09, with the labels that each got.

#1002 feat: disable `cndi run` github workflow for `dev` provider
  src/actions/overwrite.worker.ts
  src/tests/commands/ow.test.ts
  src/tests/helpers/util.ts
Labels: enhancement

#1003 Modernize and Fix `dev/microk8s`
  blocks/dev/basic-node-pool.yaml
  blocks/dev/core.md
  blocks/dev/microk8s.md
  blocks/dev/microk8s/readme-section.md
  blocks/dev/microk8s/standard-nodes.yaml
  src/actions/overwrite.worker.ts
  src/cloud-init/microk8s/leader.yml.ts
  src/constants.ts
  src/outputs/core-applications/private-nginx.application.yaml.ts
  src/outputs/core-applications/public-nginx.application.yaml.ts
  src/outputs/terraform/manifest-templates/rwm_storage_class.yaml.tftpl.ts
  src/outputs/terraform/manifest-templates/rwo_storage_class.yaml.tftpl.ts
  src/outputs/terraform/manifest-templates/storage.yaml.tftpl.ts
Labels: enhancement

#1005 Fix Manual Horizontal Node Scaling on EKS
  src/outputs/terraform/aws/AWSEKSStack.ts
Labels: bug

#1004 [Template]: minio
  templates/minio.yaml
Labels: enhancement, template

#1019 feat: respect ignoreDifferences and revisionHistoryLimit in App spec
  src/outputs/application-manifest.ts
Labels: enhancement

#1022 [Template]: `wordpress`
  src/constants.ts
  templates/wordpress.yaml
Labels: template
