Repository polyseam/cndi, pull requests merged in 2024-02, with the labels that each got.

#697 `cndi ow` will now only generate a diff if configuration changes
  deno.lock
  src/actions/overwrite.ts
  src/outputs/sealed-secret-manifest.ts
  src/types.ts
Labels: enhancement

#698 prevent crashes when calling `cndi install`
  src/cndi.ts
  src/commands/install.ts
  src/deps.ts
  src/outputs/cndi-run-workflow.ts
Labels: bug

#699 do not throw error when old-bin is absent
  src/utils.ts
Labels: bug

#713 [Enhancement]: Add pgAdmin application to PostgreSQL Template
  templates/cnpg.yaml
Labels: enhancement

#715 [Enhancement]: Add managed k8s cluster connect cli commands
  src/outputs/terraform/aws/AWSEKSStack.ts
  src/outputs/terraform/azure/AzureAKSStack.ts
  src/outputs/terraform/gcp/GCPGKEStack.ts
Labels: enhancement

#717 fix schema and outputs lnks
  README.md
Labels: documentation

#723 [Bug]: `cnpg` and `airflow` templates fail when `external_dns` is disabled
  templates/airflow.yaml
  templates/cnpg.yaml
Labels: bug

#732 [Bug]: install awscli v1 to fix `aws/eks` deployments
  src/outputs/cndi-run-workflow.ts
Labels: bug

#748 [Bug]: Fix `*/microk8s` cloud-init errors related to nfs
  src/cloud-init/microk8s/follower.yml.ts
  src/cloud-init/microk8s/leader.yml.ts
  src/outputs/terraform/aws/AWSEKSStack.ts
  src/outputs/terraform/azure/AzureAKSStack.ts
  src/outputs/terraform/gcp/GCPGKEStack.ts
  templates/airflow.yaml
Labels: bug
