Repository polyseam/cndi, pull requests merged in 2024-08, with the labels that each got.

#959 `kafka` Template
  templates/kafka.yaml
Labels: template

#962 [Feature]: Template Output `extra_files`
  docs/template-authoring.md
  src/commands/create.ts
  src/commands/init.ts
  src/use-template/mod.ts
  src/use-template/tests/mock/templates/extra_files-mock.yaml
  src/use-template/tests/mock/templates/extra_files_invalid-mock.yaml
  src/use-template/tests/template-execution.test.ts
  src/use-template/util/fs.ts
  templates/fns.yaml
Labels: enhancement

#967 [Build]: copy linux binaries for terraform and kubeseal before running tests
  .github/workflows/gh-release.yaml
  .github/workflows/main-latest.yaml
  .github/workflows/main-pull.yml
  deno.json
Labels: bug, build

#968 copy binary dependencies rather than move them
  .github/workflows/gh-release.yaml
  .github/workflows/main-latest.yaml
  .github/workflows/main-pull.yml
Labels: build

#970 enable much greater flexibilty in configuring CNDI applications
  src/outputs/application-manifest.ts
Labels: enhancement

#971 deepmerge syncPolicy; no default namespace for App CRD
  src/outputs/application-manifest.ts
Labels: enhancement

#972 [Bug]:`cndi ow` results in dead `applications` due to `valuesObject`
  src/outputs/application-manifest.ts
Labels: bug

#974 [Docs]: More `kafka` content!
  templates/kafka.yaml
Labels: documentation

#977 [Enhancement]: `cndi_config.infrastructure.cndi.open_ports` for managed clusters
  src/outputs/core-applications/public-nginx.application.yaml.ts
  src/tests/commands/init.test.ts
  src/tests/commands/ow.test.ts
  src/tests/outputs/core-applications/public-nginx.application.yaml.test.ts
  templates/cnpg.yaml
Labels: enhancement

#980 Update List of Known Templates
  blocks/common/cluster/alt-core-prompts.yaml
  blocks/common/cluster/core-prompts.yaml
  src/constants.ts
  templates/mongodb.yaml
  templates/redis.yaml
Labels: enhancement

#983 [Bug]: redis-password unlinked to cluster
  templates/redis.yaml
Labels: bug

#985 [Bug]: fix broken block import in `hop` Template
  templates/hop.yaml
Labels: bug

#988 feat: extdns: do not clobber localhost devmode loopback record
  src/outputs/core-applications/external-dns.application.yaml.ts
Labels: enhancement

#986 [Enhancement]: enable `Application` CRD with `directory` instead of `helm`
  src/outputs/application-manifest.ts
Labels: enhancement

#989 Fix Failing tests on windows
  src/tests/commands/ow.test.ts
  src/use-template/tests/template-execution.test.ts
  src/use-template/tests/template-loading.test.ts
  src/use-template/tests/template-validation.test.ts
Labels: build

#993 [Bug]: `cndi create` should validate repo slug before acting
  docs/error-code-reference.json
  src/commands/create.ts
  src/setTF_VARs.ts
  src/tests/commands/create.test.ts
  src/utils.ts
Labels: bug

#994 docs: add Kafka to readme intro
  README.md
Labels: documentation

#996 `deno.lock@4` for `deno@1.46.2`
  .github/workflows/bin-build.yaml
  .github/workflows/gh-release.yaml
  .github/workflows/main-latest.yaml
  .github/workflows/main-pull.yml
  deno.json
  deno.lock
Labels: build
