Repository polyseam/cndi, pull requests merged in 2024-04, with the labels that each got.

#809 [Fix]: Remove `--unstable` from `deno compile`
  deno.json
  src/commands/create.ts
  src/commands/init.ts
Labels: build

#811 [Enhancement]: Run `cndi --help` immediately after `cndi upgrade` to ensure fast performance upon exit
  src/cliffy-provider-gh-releases/mod.ts
  src/commands/upgrade.ts
  src/utils.ts
Labels: enhancement

#784 [Bug]: EKS Nodes are not tagged with CNDIProject
  src/outputs/terraform/aws/AWSEKSStack.ts
Labels: enhancement, aws

#817 [Enhancement]: add `--skip-push` option when using `cndi create`
  src/actions/createRepo.ts
  src/actions/overwrite.worker.ts
  src/commands/create.ts
  src/commands/init.ts
Labels: enhancement

#819 [Bug]: fix build step when using custom `--workflow-source-ref`
  src/commands/create.ts
  src/commands/init.ts
  src/outputs/cndi-run-workflow.ts
Labels: bug

#820 [Enhancement]: New readonly `cndi show-outputs` command
  src/cndi.ts
  src/commands/show-outputs.ts
Labels: enhancement

#828 [Bug]: add `dependsOn` on many resources to fix `cndi destroy` for `eks`
  src/outputs/terraform/aws/AWSEKSStack.ts
Labels: bug, aws
