Repository polyseam/cndi, pull requests merged in 2025-01, with the labels that each got.

#1096 docs: fix typos in gcp-setup
  docs/cloud-setup/gcp/gcp-setup.md
Labels: documentation

#1098 docs: update README.md to include available Templates
  README.md
Labels: documentation

#1058 [Template]: dremio
  templates/dremio.yaml
Labels: enhancement, template

#1101 [Fix]: kubeseal writes `SealedSecret` manifests as JSON despite `.yaml` filename suffix
  src/outputs/sealed-secret-manifest.ts
Labels: bug

#1102 [Docs]: Update Walkthrough for `airflow` on `dev/microk8s`
  blocks/dev/microk8s.md
  docs/walkthroughs/dev/airflow.md
Labels: documentation

#1104 fix: never assume env propagation
  src/commands/destroy.ts
  src/commands/run.ts
  src/commands/show-outputs.ts
  src/getTF_VARs.ts
  src/setTF_VARs.ts
Labels: bug

#1105 [Bug]: Terraform Variables not ingested in Windows
  src/getTF_VARs.ts
  src/outputs/cndi-run-workflow.ts
  src/outputs/terraform/CNDICoreTerraformStack.ts
  src/utils.ts
  templates/clusterless-basic.yaml
Labels: bug

#1106 provide backwards compatible TF_VAR vals
  src/getTF_VARs.ts
Labels: bug

#1107 [Bug]: Deno to v2.1.4 to fix Windows compiled binaries
  .github/workflows/bin-build.yaml
  .github/workflows/gh-release.yaml
  .github/workflows/main-latest.yaml
  .github/workflows/main-pull.yml
  deno.json
Labels: bug

#1110 feat: enable "checks" workflow
  deno.json
  deno.lock
  src/actions/overwrite.worker.ts
  src/commands/create.ts
  src/commands/init.ts
  src/commands/overwrite.ts
  src/deps.ts
  src/outputs/cndi-onpull-workflow.ts
  src/outputs/terraform/aws/AWSEKSStack.ts
  src/outputs/terraform/azure/AzureAKSStack.ts
  src/outputs/terraform/gcp/GCPGKEStack.ts
Labels: enhancement

#1115 [Enhancement]: include `fns-env-secret` example by default in `fns` Template
  src/versions.ts
  templates/fns.yaml
Labels: enhancement

#1117 build: copy binaries into release with prev. naming scheme
  .github/workflows/gh-release.yaml
Labels: build

#1119 feat: log the number of responses pulled during init/create
  src/commands/create.ts
  src/commands/init.ts
Labels: enhancement

#1120 [Enhancement]: Template aliases
  src/known-templates.ts
  src/use-template/mod.ts
Labels: enhancement
